### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by larryhe** [bezkoder/docker-compose-spring-boot-mysql#1]
keep getting below error after cloning the repo and run docker-compose up. are you able to run it successfully on local? thanks. 
```
ring-orm-5.2.1.RELEASE.jar:5.2.1.RELEASE]
docker-compose-spring-boot-mysql-app-1  | 	... 20 common frames omitted
docker-compose-spring-boot-mysql-app-1  | Caused by: java.sql.SQLException: null,  message from server: "Host '172.20.0.3' is not allowed to connect to this MySQL server"
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.4.1.jar:na]
docker-compose-spring-boot-mysql-app-1  | 	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
docker-compose-spring-boot-mysql-app-1  | 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
docker-compose-spring-boot-mysql-app-1  | 	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
docker-compose-spring-boot-mysql-app-1  | 	... 35 common frames omitted
docker-compose-spring-boot-mysql-app-1  |
docker-compose-spring-boot-mysql-app-1  | [INFO] ------------------------------------------------------------------------
docker-compose-spring-boot-mysql-app-1  | [INFO] BUILD FAILURE
```

**Comment by Ganeshjadhav221b** [comment]
No issues. Am able to run it. Any changes you've made while running locally?

**Comment by ishtiaqurrahman** [comment]
Can't access ports outside network and I have firewalls disabled on my Linux. How to run docker compose like docker run --network host?
